const blogData = [
    {
        id: 1,
        title: "The Art of Baking Bread",
        image: "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg",
        description: "Master the techniques of baking perfect bread at home.",
    },
    {
        id: 2,
        title: "10 Must-Try Pasta Recipes",
        image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
        description: "Delicious pasta dishes you need to try.",
    },
    {
        id: 3,
        title: "Secrets to Perfect Sushi Rolls",
        image: "https://images.pexels.com/photos/3298689/pexels-photo-3298689.jpeg",
        description: "Make restaurant-quality sushi at home.",
    },
    {
        id: 4,
        title: "Healthy Smoothie Recipes",
        image: "https://images.pexels.com/photos/5665662/pexels-photo-5665662.jpeg",
        description: "Boost your energy with these nutritious smoothies.",
    },
    {
        id: 5,
        title: "Homemade Pizza Guide",
        image: "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg",
        description: "Step-by-step guide to making the perfect pizza.",
    },
    {
        id: 6,
        title: "Best Street Foods Around the World",
        image: "https://images.pexels.com/photos/616404/pexels-photo-616404.jpeg",
        description: "Explore the tastiest street foods globally.",
    },
    {
        id: 7,
        title: "Vegan Dishes You’ll Love",
        image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
        description: "Delicious plant-based meals for every occasion.",
    },
    {
        id: 8,
        title: "Gourmet Desserts at Home",
        image: "https://images.pexels.com/photos/3026801/pexels-photo-3026801.jpeg",
        description: "Create elegant desserts easily.",
    },
    {
        id: 9,
        title: "BBQ Tips for Grilling Masters",
        image: "https://images.pexels.com/photos/302902/pexels-photo-302902.jpeg",
        description: "Secrets to making the best BBQ dishes.",
    },
    {
        id: 10,
        title: "Comfort Food Classics",
        image: "https://images.pexels.com/photos/616404/pexels-photo-616404.jpeg",
        description: "The best homemade comfort food recipes.",
    },
    {
        id: 11,
        title: "Healthy Salads for Every Meal",
        image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
        description: "Nutrient-packed salads for a healthy lifestyle.",
    },
    {
        id: 12,
        title: "The Science of Coffee Brewing",
        image: "https://images.pexels.com/photos/302902/pexels-photo-302902.jpeg",
        description: "How to brew the perfect cup of coffee.",
    },
    {
        id: 13,
        title: "The Best Tacos You Can Make",
        image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
        description: "Authentic taco recipes for every taste.",
    },
    {
        id: 14,
        title: "Homemade Ice Cream Ideas",
        image: "https://images.pexels.com/photos/3026800/pexels-photo-3026800.jpeg",
        description: "Cool down with these easy ice cream recipes.",
    },
    {
        id: 15,
        title: "One-Pot Meals for Busy Days",
        image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
        description: "Easy and delicious one-pot meal ideas.",
    },
    {
        id: 16,
        title: "Breakfast Ideas to Start Your Day",
        image: "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg",
        description: "Delicious breakfast recipes for a great start.",
    },
    {
        id: 17,
        title: "Gourmet Burgers at Home",
        image: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg",
        description: "Make restaurant-style burgers in your kitchen.",
    },
    {
        id: 18,
        title: "Mediterranean Diet Explained",
        image: "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg",
        description: "Why the Mediterranean diet is so healthy.",
    },
    {
        id: 19,
        title: "Delicious Soup Recipes",
        image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
        description: "Warm and comforting soup recipes.",
    },
    {
        id: 20,
        title: "Cake Decorating Like a Pro",
        image: "https://images.pexels.com/photos/5412160/pexels-photo-5412160.jpeg",
        description: "Learn cake decorating tips and tricks.",
    },
    {
        id: 21,
        title: "Cooking with Spices",
        image: "https://images.pexels.com/photos/5412160/pexels-photo-5412160.jpeg",
        description: "Enhance flavors using the right spices.",
    },
    {
        id: 22,
        title: "Making the Perfect Omelette",
        image: "https://images.pexels.com/photos/616404/pexels-photo-616404.jpeg",
        description: "Master the art of cooking an omelette.",
    },
    {
        id: 23,
        title: "Keto Diet Meal Prep",
        image: "https://images.pexels.com/photos/287827/pexels-photo-287827.jpeg",
        description: "Meal prepping for a successful keto diet.",
    },
    {
        id: 24,
        title: "Best Chocolate Recipes",
        image: "https://images.pexels.com/photos/287827/pexels-photo-287827.jpeg",
        description: "Indulge in the best chocolate treats.",
    },
    {
        id: 25,
        title: "How to Make Authentic Ramen",
        image: "https://images.pexels.com/photos/1170579/pexels-photo-1170579.jpeg",
        description: "A step-by-step guide to making ramen.",
    },
    {
        id: 26,
        title: "Homemade Sushi Guide",
        image: "https://images.pexels.com/photos/3298689/pexels-photo-3298689.jpeg",
        description: "Learn how to make sushi at home.",
    },
    {
        id: 27,
        title: "Best Indian Dishes to Cook",
        image: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg",
        description: "Popular Indian recipes for home cooks.",
    },
    {
        id: 28,
        title: "Top 10 Sandwich Recipes",
        image: "https://images.pexels.com/photos/287827/pexels-photo-287827.jpeg",
        description: "Easy and delicious sandwiches to try.",
    },
    {
        id: 29,
        title: "French Cuisine Basics",
        image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
        description: "An introduction to classic French dishes.",
    },
    {
        id: 30,
        title: "Healthy Meal Prep Tips",
        image: "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg",
        description: "How to plan and prepare healthy meals.",
    },
];

export default blogData;
